# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_configuration.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ClientConfiguration(object):
    def setupUi(self, ClientConfiguration):
        ClientConfiguration.setObjectName(_fromUtf8("ClientConfiguration"))
        ClientConfiguration.resize(835, 361)
        self.label = QtGui.QLabel(ClientConfiguration)
        self.label.setGeometry(QtCore.QRect(295, 15, 246, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(ClientConfiguration)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 151, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.max_shard_size = QtGui.QSpinBox(ClientConfiguration)
        self.max_shard_size.setGeometry(QtCore.QRect(185, 65, 246, 32))
        self.max_shard_size.setObjectName(_fromUtf8("max_shard_size"))
        self.label_3 = QtGui.QLabel(ClientConfiguration)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 361, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.connections_onetime = QtGui.QSpinBox(ClientConfiguration)
        self.connections_onetime.setGeometry(QtCore.QRect(405, 105, 96, 32))
        self.connections_onetime.setObjectName(_fromUtf8("connections_onetime"))
        self.label_5 = QtGui.QLabel(ClientConfiguration)
        self.label_5.setGeometry(QtCore.QRect(35, 190, 96, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line = QtGui.QFrame(ClientConfiguration)
        self.line.setGeometry(QtCore.QRect(505, 60, 10, 121))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.shard_size_unit = QtGui.QComboBox(ClientConfiguration)
        self.shard_size_unit.setGeometry(QtCore.QRect(440, 65, 61, 31))
        self.shard_size_unit.setObjectName(_fromUtf8("shard_size_unit"))
        self.shard_size_unit.addItem(_fromUtf8(""))
        self.shard_size_unit.addItem(_fromUtf8(""))
        self.shard_size_unit.addItem(_fromUtf8(""))
        self.shard_size_unit.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(ClientConfiguration)
        self.label_6.setGeometry(QtCore.QRect(585, 55, 166, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_2 = QtGui.QFrame(ClientConfiguration)
        self.line_2.setGeometry(QtCore.QRect(515, 85, 316, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.logout_bt = QtGui.QPushButton(ClientConfiguration)
        self.logout_bt.setGeometry(QtCore.QRect(520, 105, 311, 36))
        self.logout_bt.setObjectName(_fromUtf8("logout_bt"))
        self.line_3 = QtGui.QFrame(ClientConfiguration)
        self.line_3.setGeometry(QtCore.QRect(5, 45, 826, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.clear_logs_bt = QtGui.QPushButton(ClientConfiguration)
        self.clear_logs_bt.setGeometry(QtCore.QRect(35, 225, 151, 31))
        self.clear_logs_bt.setObjectName(_fromUtf8("clear_logs_bt"))
        self.restore_to_default_bt = QtGui.QPushButton(ClientConfiguration)
        self.restore_to_default_bt.setGeometry(QtCore.QRect(200, 225, 201, 31))
        self.restore_to_default_bt.setObjectName(_fromUtf8("restore_to_default_bt"))
        self.cancel_bt = QtGui.QPushButton(ClientConfiguration)
        self.cancel_bt.setGeometry(QtCore.QRect(690, 320, 141, 31))
        self.cancel_bt.setObjectName(_fromUtf8("cancel_bt"))
        self.apply_bt = QtGui.QPushButton(ClientConfiguration)
        self.apply_bt.setGeometry(QtCore.QRect(480, 320, 201, 31))
        self.apply_bt.setObjectName(_fromUtf8("apply_bt"))
        self.advanced_view_checkBox = QtGui.QCheckBox(ClientConfiguration)
        self.advanced_view_checkBox.setGeometry(QtCore.QRect(35, 265, 146, 22))
        self.advanced_view_checkBox.setObjectName(_fromUtf8("advanced_view_checkBox"))
        self.line_4 = QtGui.QFrame(ClientConfiguration)
        self.line_4.setGeometry(QtCore.QRect(5, 295, 826, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(ClientConfiguration)
        self.line_5.setGeometry(QtCore.QRect(5, 175, 821, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_4 = QtGui.QLabel(ClientConfiguration)
        self.label_4.setGeometry(QtCore.QRect(425, 205, 206, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line_6 = QtGui.QFrame(ClientConfiguration)
        self.line_6.setGeometry(QtCore.QRect(410, 180, 10, 121))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.max_download_bandwidth = QtGui.QLineEdit(ClientConfiguration)
        self.max_download_bandwidth.setGeometry(QtCore.QRect(630, 200, 141, 36))
        self.max_download_bandwidth.setObjectName(_fromUtf8("max_download_bandwidth"))
        self.max_upload_bandwidth = QtGui.QLineEdit(ClientConfiguration)
        self.max_upload_bandwidth.setGeometry(QtCore.QRect(630, 245, 141, 36))
        self.max_upload_bandwidth.setObjectName(_fromUtf8("max_upload_bandwidth"))
        self.label_7 = QtGui.QLabel(ClientConfiguration)
        self.label_7.setGeometry(QtCore.QRect(440, 245, 186, 36))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(ClientConfiguration)
        self.label_8.setGeometry(QtCore.QRect(780, 205, 46, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(ClientConfiguration)
        self.label_9.setGeometry(QtCore.QRect(780, 245, 46, 36))
        self.label_9.setObjectName(_fromUtf8("label_9"))

        self.retranslateUi(ClientConfiguration)
        self.shard_size_unit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ClientConfiguration)

    def retranslateUi(self, ClientConfiguration):
        ClientConfiguration.setWindowTitle(_translate("ClientConfiguration", "Storj Uploader Configuration", None))
        self.label.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Settings - Storj GUI Client</span></p></body></html>", None))
        self.label_2.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Max size of shard:</span></p></body></html>", None))
        self.label_3.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Number of active connections at the same time:</span></p></body></html>", None))
        self.label_5.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Advanced</span></p></body></html>", None))
        self.shard_size_unit.setItemText(0, _translate("ClientConfiguration", "MB", None))
        self.shard_size_unit.setItemText(1, _translate("ClientConfiguration", "GB", None))
        self.shard_size_unit.setItemText(2, _translate("ClientConfiguration", "TB", None))
        self.shard_size_unit.setItemText(3, _translate("ClientConfiguration", "PB", None))
        self.label_6.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Account options</span></p></body></html>", None))
        self.logout_bt.setText(_translate("ClientConfiguration", "Logout", None))
        self.clear_logs_bt.setText(_translate("ClientConfiguration", "Clear logs", None))
        self.restore_to_default_bt.setText(_translate("ClientConfiguration", "Restore settings to default", None))
        self.cancel_bt.setText(_translate("ClientConfiguration", "Cancel", None))
        self.apply_bt.setText(_translate("ClientConfiguration", "Apply", None))
        self.advanced_view_checkBox.setText(_translate("ClientConfiguration", "Advanced view", None))
        self.label_4.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Max download bandwidth:</span></p></body></html>", None))
        self.label_7.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Max upload bandwidth:</span></p></body></html>", None))
        self.label_8.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Mbps</span></p></body></html>", None))
        self.label_9.setText(_translate("ClientConfiguration", "<html><head/><body><p><span style=\" font-size:12pt;\">Mbps</span></p></body></html>", None))

