# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_file_upload.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SingleFileUpload(object):
    def setupUi(self, SingleFileUpload):
        SingleFileUpload.setObjectName(_fromUtf8("SingleFileUpload"))
        SingleFileUpload.resize(1168, 610)
        self.line_3 = QtGui.QFrame(SingleFileUpload)
        self.line_3.setGeometry(QtCore.QRect(20, 50, 1141, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label = QtGui.QLabel(SingleFileUpload)
        self.label.setGeometry(QtCore.QRect(10, 10, 1151, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(SingleFileUpload)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 41))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(SingleFileUpload)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 91, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.file_path_select_bt = QtGui.QPushButton(SingleFileUpload)
        self.file_path_select_bt.setGeometry(QtCore.QRect(530, 110, 61, 31))
        self.file_path_select_bt.setObjectName(_fromUtf8("file_path_select_bt"))
        self.file_path = QtGui.QLineEdit(SingleFileUpload)
        self.file_path.setGeometry(QtCore.QRect(160, 110, 361, 31))
        self.file_path.setObjectName(_fromUtf8("file_path"))
        self.line = QtGui.QFrame(SingleFileUpload)
        self.line.setGeometry(QtCore.QRect(593, 60, 20, 541))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.start_upload_bt = QtGui.QPushButton(SingleFileUpload)
        self.start_upload_bt.setGeometry(QtCore.QRect(10, 230, 581, 51))
        self.start_upload_bt.setObjectName(_fromUtf8("start_upload_bt"))
        self.label_4 = QtGui.QLabel(SingleFileUpload)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 211, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(SingleFileUpload)
        self.label_5.setGeometry(QtCore.QRect(30, 360, 91, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(SingleFileUpload)
        self.label_6.setGeometry(QtCore.QRect(30, 390, 101, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(SingleFileUpload)
        self.label_7.setGeometry(QtCore.QRect(30, 420, 71, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(SingleFileUpload)
        self.label_8.setGeometry(QtCore.QRect(610, 60, 551, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cancel_bt = QtGui.QPushButton(SingleFileUpload)
        self.cancel_bt.setGeometry(QtCore.QRect(310, 290, 281, 31))
        self.cancel_bt.setObjectName(_fromUtf8("cancel_bt"))
        self.upload_log_bt = QtGui.QPushButton(SingleFileUpload)
        self.upload_log_bt.setGeometry(QtCore.QRect(10, 290, 291, 31))
        self.upload_log_bt.setObjectName(_fromUtf8("upload_log_bt"))
        self.tmp_path = QtGui.QLineEdit(SingleFileUpload)
        self.tmp_path.setGeometry(QtCore.QRect(220, 150, 301, 31))
        self.tmp_path.setObjectName(_fromUtf8("tmp_path"))
        self.tmp_path_select_bt = QtGui.QPushButton(SingleFileUpload)
        self.tmp_path_select_bt.setGeometry(QtCore.QRect(530, 150, 61, 31))
        self.tmp_path_select_bt.setObjectName(_fromUtf8("tmp_path_select_bt"))
        self.label_9 = QtGui.QLabel(SingleFileUpload)
        self.label_9.setGeometry(QtCore.QRect(50, 150, 161, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(SingleFileUpload)
        self.label_10.setGeometry(QtCore.QRect(610, 330, 551, 41))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_2 = QtGui.QFrame(SingleFileUpload)
        self.line_2.setGeometry(QtCore.QRect(610, 365, 551, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_11 = QtGui.QLabel(SingleFileUpload)
        self.label_11.setGeometry(QtCore.QRect(610, 380, 141, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.overall_progress = QtGui.QProgressBar(SingleFileUpload)
        self.overall_progress.setGeometry(QtCore.QRect(760, 380, 401, 31))
        self.overall_progress.setProperty("value", 24)
        self.overall_progress.setObjectName(_fromUtf8("overall_progress"))
        self.label_12 = QtGui.QLabel(SingleFileUpload)
        self.label_12.setGeometry(QtCore.QRect(610, 420, 81, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(SingleFileUpload)
        self.label_13.setGeometry(QtCore.QRect(610, 450, 81, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(SingleFileUpload)
        self.label_14.setGeometry(QtCore.QRect(610, 480, 141, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(SingleFileUpload)
        self.label_15.setGeometry(QtCore.QRect(10, 510, 181, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(SingleFileUpload)
        self.label_16.setGeometry(QtCore.QRect(30, 540, 161, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.avg_bandwidth = QtGui.QLabel(SingleFileUpload)
        self.avg_bandwidth.setGeometry(QtCore.QRect(200, 540, 391, 31))
        self.avg_bandwidth.setObjectName(_fromUtf8("avg_bandwidth"))
        self.label_18 = QtGui.QLabel(SingleFileUpload)
        self.label_18.setGeometry(QtCore.QRect(30, 450, 111, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.shardsize = QtGui.QLabel(SingleFileUpload)
        self.shardsize.setGeometry(QtCore.QRect(130, 360, 401, 31))
        self.shardsize.setObjectName(_fromUtf8("shardsize"))
        self.shards_count = QtGui.QLabel(SingleFileUpload)
        self.shards_count.setGeometry(QtCore.QRect(140, 390, 401, 31))
        self.shards_count.setObjectName(_fromUtf8("shards_count"))
        self.file_size = QtGui.QLabel(SingleFileUpload)
        self.file_size.setGeometry(QtCore.QRect(110, 420, 401, 31))
        self.file_size.setObjectName(_fromUtf8("file_size"))
        self.file_frame_id = QtGui.QLabel(SingleFileUpload)
        self.file_frame_id.setGeometry(QtCore.QRect(150, 450, 441, 31))
        self.file_frame_id.setObjectName(_fromUtf8("file_frame_id"))
        self.uploaded_data = QtGui.QLabel(SingleFileUpload)
        self.uploaded_data.setGeometry(QtCore.QRect(700, 420, 401, 31))
        self.uploaded_data.setObjectName(_fromUtf8("uploaded_data"))
        self.data_to_upload_remaianing = QtGui.QLabel(SingleFileUpload)
        self.data_to_upload_remaianing.setGeometry(QtCore.QRect(700, 450, 401, 31))
        self.data_to_upload_remaianing.setObjectName(_fromUtf8("data_to_upload_remaianing"))
        self.shards_uploaded = QtGui.QLabel(SingleFileUpload)
        self.shards_uploaded.setGeometry(QtCore.QRect(760, 480, 401, 31))
        self.shards_uploaded.setObjectName(_fromUtf8("shards_uploaded"))
        self.label_23 = QtGui.QLabel(SingleFileUpload)
        self.label_23.setGeometry(QtCore.QRect(30, 480, 101, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.push_token = QtGui.QLabel(SingleFileUpload)
        self.push_token.setGeometry(QtCore.QRect(140, 480, 451, 31))
        self.push_token.setObjectName(_fromUtf8("push_token"))
        self.current_state = QtGui.QLabel(SingleFileUpload)
        self.current_state.setGeometry(QtCore.QRect(730, 510, 431, 31))
        self.current_state.setObjectName(_fromUtf8("current_state"))
        self.label_19 = QtGui.QLabel(SingleFileUpload)
        self.label_19.setGeometry(QtCore.QRect(610, 510, 121, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(SingleFileUpload)
        self.label_20.setGeometry(QtCore.QRect(220, 70, 151, 31))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.save_to_bucket_select = QtGui.QComboBox(SingleFileUpload)
        self.save_to_bucket_select.setGeometry(QtCore.QRect(370, 70, 221, 31))
        self.save_to_bucket_select.setObjectName(_fromUtf8("save_to_bucket_select"))
        self.encrypt_files_checkbox = QtGui.QCheckBox(SingleFileUpload)
        self.encrypt_files_checkbox.setGeometry(QtCore.QRect(420, 200, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.encrypt_files_checkbox.setFont(font)
        self.encrypt_files_checkbox.setChecked(True)
        self.encrypt_files_checkbox.setTristate(False)
        self.encrypt_files_checkbox.setObjectName(_fromUtf8("encrypt_files_checkbox"))
        self.current_state_2 = QtGui.QLabel(SingleFileUpload)
        self.current_state_2.setGeometry(QtCore.QRect(730, 530, 431, 41))
        self.current_state_2.setObjectName(_fromUtf8("current_state_2"))
        self.label_21 = QtGui.QLabel(SingleFileUpload)
        self.label_21.setGeometry(QtCore.QRect(30, 570, 131, 31))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.active_transfers = QtGui.QLabel(SingleFileUpload)
        self.active_transfers.setGeometry(QtCore.QRect(170, 570, 391, 31))
        self.active_transfers.setObjectName(_fromUtf8("active_transfers"))
        self.shard_queue_table_widget = QtGui.QTableWidget(SingleFileUpload)
        self.shard_queue_table_widget.setGeometry(QtCore.QRect(610, 100, 551, 231))
        self.shard_queue_table_widget.setObjectName(_fromUtf8("shard_queue_table_widget"))
        self.shard_queue_table_widget.setColumnCount(0)
        self.shard_queue_table_widget.setRowCount(0)

        self.retranslateUi(SingleFileUpload)
        QtCore.QMetaObject.connectSlotsByName(SingleFileUpload)

    def retranslateUi(self, SingleFileUpload):
        SingleFileUpload.setWindowTitle(_translate("SingleFileUpload", "Upload file - Storj GUI Client", None))
        self.label.setText(_translate("SingleFileUpload", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Single file upload - Storj GUI Client</span></p></body></html>", None))
        self.label_2.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Select file</span></p></body></html>", None))
        self.label_3.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">File path:</span></p></body></html>", None))
        self.file_path_select_bt.setText(_translate("SingleFileUpload", "Select...", None))
        self.start_upload_bt.setText(_translate("SingleFileUpload", "Start file upload process", None))
        self.label_4.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Shards and file details</span></p></body></html>", None))
        self.label_5.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Shard size:</span></p></body></html>", None))
        self.label_6.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Shard count:</span></p></body></html>", None))
        self.label_7.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">File size:</span></p></body></html>", None))
        self.label_8.setText(_translate("SingleFileUpload", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Shard upload queue progress</span></p></body></html>", None))
        self.cancel_bt.setText(_translate("SingleFileUpload", "Cancel", None))
        self.upload_log_bt.setText(_translate("SingleFileUpload", "Open upload log", None))
        self.tmp_path_select_bt.setText(_translate("SingleFileUpload", "Select...", None))
        self.label_9.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Temporary path:</span></p></body></html>", None))
        self.label_10.setText(_translate("SingleFileUpload", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Progress status</span></p></body></html>", None))
        self.label_11.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Overall progress:</span></p></body></html>", None))
        self.label_12.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Uploaded:</span></p></body></html>", None))
        self.label_13.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">To upload:</span></p></body></html>", None))
        self.label_14.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Shards uploaded:</span></p></body></html>", None))
        self.label_15.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Network statistics</span></p></body></html>", None))
        self.label_16.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Average bandwidth:</span></p></body></html>", None))
        self.avg_bandwidth.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.label_18.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">File frame ID:</span></p></body></html>", None))
        self.shardsize.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.shards_count.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.file_size.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.file_frame_id.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.uploaded_data.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.data_to_upload_remaianing.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.shards_uploaded.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.label_23.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">PUSH Token:</span></p></body></html>", None))
        self.push_token.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.current_state.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))
        self.label_19.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Current state:</span></p></body></html>", None))
        self.label_20.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Save in bucket:</span></p></body></html>", None))
        self.encrypt_files_checkbox.setText(_translate("SingleFileUpload", "Encrypt shards", None))
        self.current_state_2.setText(_translate("SingleFileUpload", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_21.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Active transfers:</span></p></body></html>", None))
        self.active_transfers.setText(_translate("SingleFileUpload", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Waiting...</span></p></body></html>", None))

